CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NOMBRECOMPLETO VARCHAR(100) NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    NACIMIENTO DATE NOT NULL,
    IMAGEN VARCHAR(100) NOT NULL,
    PUNTOS INT NOT NULL,
    PRIMARY KEY(ID)
);


CREATE TABLE FRIENDS (
    ID1 INT NOT NULL,
    ID2 INT NOT NULL,
    ACCEPTED BOOLEAN NOT NULL,
    FOREIGN KEY(ID1) REFERENCES USERS(ID),
    FOREIGN KEY(ID2) REFERENCES USERS(ID),
    PRIMARY KEY(ID1,ID2)
);

CREATE TABLE QUESTIONS (
    ID INT NOT NULL AUTO_INCREMENT,
    PREGUNTA VARCHAR(200) NOT NULL,
    NUM_RESPUESTAS_INICIAL INT NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ANSWERS (
    ID_PREGUNTA INT NOT NULL,
    RESPUESTA VARCHAR(200),
    FOREIGN KEY(ID_PREGUNTA) REFERENCES QUESTIONS(ID),
    PRIMARY KEY(ID_PREGUNTA, RESPUESTA)
);

CREATE TABLE ANSWER_USER (
    ID_PREGUNTA INT NOT NULL,
    ID_USER INT NOT NULL,
    RESPUESTA VARCHAR(200),
    FOREIGN KEY(ID_PREGUNTA) REFERENCES QUESTIONS(ID),
    FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
    PRIMARY KEY(ID_USER, ID_PREGUNTA)
);

CREATE TABLE USER_ANSWER_USER (
    ID_PREGUNTA INT NOT NULL,
    ID_PLAYER INT NOT NULL,
    ID_OTHER INT NOT NULL,
    CORRECT BOOLEAN NOT NULL,
    FOREIGN KEY(ID_PREGUNTA) REFERENCES QUESTIONS(ID),
    FOREIGN KEY(ID_PLAYER) REFERENCES USERS(ID),
    FOREIGN KEY(ID_OTHER) REFERENCES USERS(ID),
    PRIMARY KEY(ID_PREGUNTA, ID_PLAYER, ID_OTHER)
)
