CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NOMBRECOMPLETO VARCHAR(100) NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    NACIMIENTO DATE NOT NULL,
    IMAGEN VARCHAR(100) NOT NULL,
    PUNTOS INT NOT NULL,
    PRIMARY KEY(ID)
);


CREATE TABLE FRIENDS (
    ID1 INT NOT NULL,
    ID2 INT NOT NULL,
    ACCEPTED BOOLEAN NOT NULL,
    FOREIGN KEY(ID1) REFERENCES USERS(ID),
    FOREIGN KEY(ID2) REFERENCES USERS(ID),
    PRIMARY KEY(ID1,ID2)
)